name: CI

on:
	push:
		branches:
			- main
			
jobs:
		build-and-push: 
			name: 'Build and Push'
			runs-on: ubuntu-latest
			
			steps:
			- name: Checkout
				uses: actions/checkout@v4

			- name: Generate SHA
				id: generate_sha
				run: |
					SHA=$(echo $GITHUB_SHA | head -c7)
					echo "sha=$SHA" >> $GITHUB_OUTPUT
				
				# gerar tag de acordo com commit
				
			- name: Build docker image
				#run: docker build -t api-journey:v2 .
				# Não pode colocar "latest"
				run: docker build -t gustrpaz/nlw.journey.api:${{ steps.generate_sha.outputs.sha }} .
				
				# Logar no container registry
				# Enviar imagem após
